### ISSUE TITLE
Aumentar compatibilidade com outros browsers

### ISSUE THREAD

**Issue by lpereira** [lpereira/Pense-Bem#5]
Nem todos os browsers (mesmo versões recentes, como Safari 5), conseguem exibir SVG inline como está sendo usado no simulador. Encontrar formas alternativas de fazer isso funcionar em outros browsers.

**Comment by denilsonsa** [comment]
Acho que podemos fechar este "issue", os browsers já são modernos o suficiente. https://caniuse.com/#feat=svg-html5

**Comment by lpereira** [comment]
De fato. Fechando.
